config/routes.rb
Rails.application.routes.draw do
  resources :methodologies
  resources :dev_methods
  resources :research_methods
  resources :statuses
  resources :authors
  resources :articles
  resources :article_types
  resources :ratings
  resources :feedbacks
  resources :research_participants
  resources :roles
  resources :users
  resources :tests
  resources :searches
  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :status

  # TETSINGGGGGGG
    def self.search(search)
        if search
          where(["title LIKE ?","%#{search}%"])
        else
          all
        end
    end

end

app/models/article_type.rb
class ArticleType < ActiveRecord::Base
end

app/models/articles_author.rb
class ArticlesAuthor < ActiveRecord::Base
end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/dev_method.rb
class DevMethod < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

  # Trung - Define model associations
  belongs_to :user

end

app/models/methodology.rb
class Methodology < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/research_method.rb
class ResearchMethod < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base

  # Trung - Define model associations
  has_many :users_roles, foreign_key: :role_id

end

app/models/search.rb
class Search < ActiveRecord::Base
    def search_articles
        articles = Article.all
        articles = articles.where(["title LIKE ?", "%#{keywords}%"]) if keywords.present?
        articles = articles.where(["journal LIKE ?",fields]) if fields.present?
        return articles
    end
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base

  # Trung - Define model associations
  has_many :users_roles, foreign_key: :user_id
  has_many :feedbacks, foreign_key: :user_id

  #Quang attribute accessor
  attr_accessor :first_name, :middle_name, :last_name, :email, :gender, :dob, :affiliation, :is_active

end

app/models/users_role.rb
class UsersRole < ActiveRecord::Base

  # Trung - Define model associations
  belongs_to :user
  belongs_to :role

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    # @articles = Article.all
    @articles = Article.search(params[:search])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :journal, :year, :pages)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %><br>
    </p>

    <p>
      <%= f.label :journal %>
      <%= f.text_field :journal %><br>
    </p>

    <p>
      <%= f.label :year %>
      <%= f.text_field :year %><br>
    </p>
    <p>
      <%= f.label :pages %>
      <%= f.text_field :pages %><br>
    </p>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>


<%= form_tag articles_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
<% end %>

<%= link_to "Advanced Search", new_search_path %>


  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Custom responsive table </h5>
          <div class="ibox-tools">
            <a class="collapse-link">
              <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-wrench"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
              <li><a href="#">Config option 1</a>
              </li>
              <li><a href="#">Config option 2</a>
              </li>
            </ul>
            <a class="close-link">
              <i class="fa fa-times"></i>
            </a>
          </div>
        </div>
        <div class="ibox-content">
          <div class="row">
            <div class="col-sm-5 m-b-xs">
              <select class="input-sm form-control input-s-sm inline">
              <option value="0">Option 1</option>
              <option value="1">Option 2</option>
              <option value="2">Option 3</option>
              <option value="3">Option 4</option>
            </select>
            </div>
            <div class="col-sm-4 m-b-xs">
              <div data-toggle="buttons" class="btn-group">
                <label class="btn btn-sm btn-white"> <input type="radio" id="option1" name="options"> Day </label>
                <label class="btn btn-sm btn-white active"> <input type="radio" id="option2" name="options"> Week </label>
                <label class="btn btn-sm btn-white"> <input type="radio" id="option3" name="options"> Month </label>
              </div>
            </div>


            <div class="col-sm-3">
              <form action="/articles" method="get">
              <div class="input-group">
                  <input type="text" placeholder="Search" name="search" class="input-sm form-control"> <span class="input-group-btn">
                  <button type="submit" class="btn btn-sm btn-primary"> Go!</button> </span>
              </div>
              </form>
            </div>
          </div>
          <div class="table-responsive">
            <div class="column-view">
                <label style="font-weight:bold;">Filter: </label>
                <label><input type="checkbox" class="check-head" value="1" name="title" checked="checked"><span>Title</span></label>
                <label><input type="checkbox" class="check-head" value="1" name="journal" checked="checked"><span>Journal</span></label>
                <label><input type="checkbox" class="check-head" value="1" name="year" checked="checked"><span>Year</span></label>
                <label><input type="checkbox" class="check-head" value="1" name="volume" checked="checked"><span>Volume</span></label>
                <label><input type="checkbox" class="check-head" value="1" name="pages" checked="checked"><span>Pages</span></label>
            </div>
              <table class="table table-striped">
              <thead>
              <tr>
                <th></th>
                <th class="title">Title </th>
                <th class="journal">Journal </th>
                <th class="year">Year</th>
                <th class="volume">Volume</th>
                <th class="pages">Pages</th>
              </tr>
              </thead>
              <tbody>
              <% @articles.each do |article| %>
              <tr>
                <td><div class="icheckbox_square-green checked" style="position: relative;"><input type="checkbox" checked="" class="i-checks" name="input[]" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins></div></td>
                <td class="title"><b><%= link_to article.title, article %></b> <p><small><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>, <%= link_to 'Edit', edit_article_path(article) %></small></p></td>
                <td class="journal"><%= article.journal %></td>
                <td class="year"><%= article.year %></td>
                <td class="volume">2</td>
                <td class="pages"><%= article.pages %></td>
              </tr>
              <% end %>
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>

  </div>

<br>

<%= link_to 'New Article', new_article_path %>

<script type="text/javascript">
  $(document).ready(function(){

    $(".check-head:checkbox:not(:checked)").each(function(){
      var col = "table ." + $(this).attr("name");
      $(col).hide();
    });

    $(".check-head:checkbox").click(function(){
      var col = "table ." + $(this).attr("name");
      $(col).toggle();
    });

  });

</script>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>show Title:</strong>
  <%= @article.title %> <%= @article.journal %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>